apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dropbox.fullname" . }}-config
  labels:
    {{- include "dropbox.labels" . | nindent 4 }}
data:
  # Spring profili
  SPRING_PROFILES_ACTIVE: {{ .Values.app.profile | quote }}

  # Datasource — şifre Secret'tan gelir, burada yok
  SPRING_DATASOURCE_URL: {{ include "dropbox.jdbcUrl" . | quote }}

  # Upload dizini
  APP_UPLOAD_DIR: {{ .Values.app.uploadDir | quote }}

  # Actuator — K8s probe'ları için health endpoint açık olmalı
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.app.actuator.exposedEndpoints | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"

  # Server portu
  SERVER_PORT: {{ .Values.app.port | quote }}