{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dropbox.fullname" . }}
  labels:
    {{- include "dropbox.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"   # dosya upload için limit
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    {{- if .Values.ingress.tls }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # prod TLS
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dropbox.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}