{{- if .Values.mysql.primary.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dropbox.fullname" . }}-mysql-data
  labels:
    {{- include "dropbox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.primary.persistence.size }}
  {{- end }}

