apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}-mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # aynı anda 1 yeni pod ayağa kalk
      maxUnavailable: 0  # sıfır kesinti — prod için kritik
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
      annotations:
        # ConfigMap değişince pod'ları otomatik yeniden başlat
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dropbox.fullname" . }}-mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dropbox.fullname" . }}-mysql-config
                  key: MYSQL_USER
                  
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dropbox-secret
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dropbox-secret
                  key: mysql-password
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          {{- end }}

        # ── Volumes ──────────────────────────────────────────────────────────────
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "dropbox.fullname" . }}-mysql-data
        {{- end }}