server {
    listen 80;
    server_name dev.dropbox.local;

    access_log /var/log/nginx/dev_access.log;

    location / {
        proxy_pass http://dropbox-app-dev:8085;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}