apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dropbox
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: dropbox=aysebeyaz/dropbox
    argocd-image-updater.argoproj.io/dropbox.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/dropbox.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/dropbox.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/b-beyaz/devops-ai-platform.git
    targetRevision: main
    path: infra/k8s/helm/dropbox
  destination:
    server: https://kubernetes.default.svc
    namespace: dropbox-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true