apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: dropbox-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      branch: "main"
      repository: "git@github.com:b-beyaz/devops-ai-platform.git"
      writeBackTarget: "helmvalues:values.yaml"
  applicationRefs:
    - namePattern: "dropbox*"
      images:
        - alias: "dropbox"
          imageName: "aysebeyaz/dropbox"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
  commonUpdateSettings:
    updateStrategy: "newest-build"